best_parameters:
  LSTM:
  NN:
  random_forest:
parameters:
  LSTM:
    hidden_size:
    - 32
    - 64
    - 128
    - 256
    - 512
    lr:
    - 0.1
    - 0.05
    n_layers:
    - 1
    - 2
    - 3
  NN:
    batch_norm:
    - true
    - false
    hidden_size:
    - 32
    - 64
    - 128
    - 256
    - 512
    lr:
    - 0.1
    - 0.05
    n_layers:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  random_forest:
    max_depth:
    - 3
    - 5
    - 7
    - 9
    - 10
    - 15
    n_estimators:
    - 100
    - 200
    - 300
    - 400
    - 500
    - 600
    - 700
    - 800
    - 900
    - 1000